### ISSUE TITLE
Team management

### ISSUE THREAD

**Issue by kzalys** [unicsmcr/hs_application#2]
Applicants need to be able to:
 - [ ] create a team
 - [ ] join a team
 - [ ] leave a team, a team should get automatically deleted if all people leave it

Joining a team could be handled by having a unique token for each team. So when someone creates a team, they got the token of their team, they send the token to their teammates who then then use the token to join the team. This way we don't need any complex invitation system, people simply share the token for their team.

The teams should also be cached.

**Comment by seanjparker** [comment]
This is handled in hs_auth
