### ISSUE TITLE
Invitations

### ISSUE THREAD

**Issue by kzalys** [unicsmcr/hs_application#3]
We need to be able to invite people.

Users with Organizer authorization level would have access to:
 - [x] a method that would invite a single person
 - [ ] a method that would invite a whole team (with the given team token)

The invitation method should:
 - [x] send an invitation via email, the email would probably be sent through SendGrid
 - [ ] update the backups on Dropbox

The invitations should expire after a set a amount of time (we could do this by just sending a request to the API that expires all old invitations, the request would be sent out by a cron job that gets run once a day).

Applicants need to be able to cancel their invitations

The invitation email should contain a ticket in the form of a QR code and some backup token if the QR code doesn't work (this could be done similarly to how the hardware library works where the QR code is  just a token, not a URL and then we have the same token written underneath the QR code).

**Comment by seanjparker** [comment]
Closed in favour of #25
