### ISSUE TITLE
Rewrite mail service

### ISSUE THREAD

**Issue by seanjparker** [unicsmcr/hs_application#49]
The mail service needs a complete rewrite, it is a mess of code and it would be better for a complete rewrite to make it more extensible and easier to add other templates/emails.

**Comment by kzalys** [comment]
Since we need email or push notification features on all services, I'd say a more long-term solution would be to centralize this functionality across the entire Hacker Suite and have a dedicated service for emails and push notifications.

This would also involve quite a major change to hs_auth since we'd need to add support for API keys because services would have to call other services without relying on the user's auth token (mainly because sending an email after registration would require a higher auth level than the auth level of the user who just registered).

It would be quite a bit of work but I could implement this over the summer. If anyone wants to join that'd be fantastic too.

**Comment by seanjparker** [comment]
I remember this was mentioned last year that we should split this into its own service, I think now is a good time to do it :)

Also, I don't mind helping wherever I can with changes to hs_auth

> add support for API keys because services would have to call other services without relying on the user's auth token

This would also make using the hs_discord services much easier since they currently use an organiser level auth token which we needed to refresh every 30 hours.

What do you think about this @amishshah?

**Comment by kzalys** [comment]
> they currently use an organiser level auth token

Yeah this is another reason to rework how hs_auth deals with authorization.

We need more granularity in terms of how much permissions we're giving to a token. An organiser token has quite a bit of power and it'd be best if it was only used by actual organisers.

What I suggest is that we switch from auth level based authorization to auth group based authorization. Each token could have access to multiple auth groups and each auth group would provide permissions to use a specific subset of the system's functionality.

For example: an organiser could belong to auth groups: "user", "volunteer", "organiser" and the discord services could use a token with access to the group "discord". Then we could limit that the operation to delete users for example would only be accessible with a token that has the "organiser" group and the "discord" group would have access to a list of all users (or whatever else it may need)

This way we could make sure that the discord services have access to all of the functionality they need but at the same time they can't delete users whenever they feel like it.

**Comment by amishshah** [comment]
> What do you think about this @amishshah?

This change would be great! I think the auth groups are a great idea too.

Does that mean that tokens could exist without requiring users linked to them (i.e. not require the "user" auth group)? This would make it easier to integrate into the Discord services.

**Comment by kzalys** [comment]
> Does that mean that tokens could exist without requiring users linked to them (i.e. not require the "user" auth group)? This would make it easier to integrate into the Discord services.

Yeah we'd have support for API tokens which wouldn't need to be associated with any object in the database and wouldn't expire (though the expiration time could still be configurable).

Then we could have some sort of GUI in the hs_auth admin tools to generate API tokens. So you'd fire up hs_auth and then generate the tokens for other services.

I'll try to write a design doc so we can discuss this in a bit of a more structured fashion.

**Comment by kzalys** [comment]
The design doc: https://github.com/unicsmcr/hs_auth/issues/63

**Comment by seanjparker** [comment]
Closing for now
